### PR TITLE
docs(sphinx): Add sphinx documentation  including custom CLI docs

### PR DESCRIPTION
**Pull request by santiagogaray**
Hey  @chriswmackey, 

There is a new variation here that I would like to run through you. CLI is implemented with a cli.py file at the root folder instead of an ``__index__.py`` inside a`` \cli`` subfolder. The CLI documentation process always looks for a ``\cli`` subfolder and in this case thinks there is no CLI files to document.

Which is the best way to handle this:
1- By moving/renaming the ``cli.py`` as ``\cli\__init__.py`` (IMPORTANT: This PR is doing this!!)
2- By adding support for this configuration. (if you see this possibly happening in the future, we should then do this)

Otherwise, everything else looks good. Let me know when you get a chance!

### CODE REVIEW

**Review by chriswmackey — APPROVED** [review]
Thanks @santiagogaray . The current implementation looks good and, yes, I think that repos having a single `cli.py` module should work the same as those with just a `cli/__init__.py`. If the CLI for this repo ever gets fleshed out into something larger, then it's effectively going to move everything into the `cli.py` to `cli/__init__.py`.

**Comment by chriswmackey** [comment]
Ah wait. I didn't realize that you had actually changed the CLI module. I thought you just meant that the docs were treating the `cli.py` the same as `cli/__init__.py`.

I am ok with the module name change but maybe we should make sure @mostaphaRoudsari is ok with it. I have a feeling that he might ask to have the docs script treat the `cli.py` module the same as `cli/__init__.py`.

**Comment by santiagogaray** [comment]
Hi @chriswmackey,

Since it wasn't a major effort I decided to go ahead and add support for single cli.py. I guess it won't hurt to include this and not worry about this situation coming up in future repos. 
I tested it out in many repos and seems to work fine so far.

**Comment by mostaphaRoudsari** [comment]
Hi @santiagogaray and @chriswmackey, looks like you don't need me here anymore but since I have your attention I wanted to let you know that the search functionality in documentations is broken. Try [this one](https://www.ladybug.tools/ladybug-geometry/docs/search.html?q=vector3d&check_keywords=yes&area=default) as an example.

**Review by chriswmackey — APPROVED** [review]
Thanks, @santiagogaray . Let's merge this, then.

And goo point, @mostaphaRoudsari . The search feature has not worked for as long as I can remember and it's pretty important. @santiagogaray , would you be able to investigate what's going on here before moving on to the GitBook tasks?

**Comment by santiagogaray** [comment]
Hi @mostaphaRoudsari and @chriswmackey,

Wow! Big issue there, I will definitely look into it and report back with any findings!
Thanks @chriswmackey for merging, I will hold off from updating ladybug-tools-template until we solve this key issue.

**Comment by santiagogaray** [comment]
Hi @mostaphaRoudsari and @chriswmackey, 
This bug was introduced inSphinx 3.40 by [this fix](https://github.com/sphinx-doc/sphinx/pull/8445). Luckily very smart people fixed it inside the rtd-theme which can be easily ported to our bootstrap-theme.
Bottom-line: We need to add a line of code in `sphinx_bootstrap_theme/bootstrap/search.html`, as shown [here](https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/213/commits/cc3aed240be57f9faeffdce0659dda852316c306)
I tested it out in a couple of documents without problems. Let me know if have any issues!

**Pull request merged**
